<html>
    <head>
    
    <meta charset="UTF-8" />
    <title>Find a route using Geolocation and Google Maps API</title>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script>
      function calculateRoute(from, to) {
        // Center initialized to Naples, Italy
        var myOptions = {
          zoom: 10,
          center: new google.maps.LatLng(40.84, 14.25),
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        // Draw the map
        var mapObject = new google.maps.Map(document.getElementById("map"), myOptions);

        var directionsService = new google.maps.DirectionsService();
        var directionsRequest = {
          origin: from,
          destination: to,
          travelMode: google.maps.DirectionsTravelMode.DRIVING,
          unitSystem: google.maps.UnitSystem.METRIC
        };
        directionsService.route(
          directionsRequest,
          function(response, status)
          {
            if (status == google.maps.DirectionsStatus.OK)
            {
              new google.maps.DirectionsRenderer({
                map: mapObject,
                directions: response
              });
            }
            else
              $("#error").append("Unable to retrieve your route<br />");
          }
        );
      }

      $(document).ready(function() {
        // If the browser supports the Geolocation API
        if (typeof navigator.geolocation == "undefined") {
          $("#error").text("Your browser doesn't support the Geolocation API");
          return;
        }

        $("#from-link, #to-link").click(function(event) {
          event.preventDefault();
          var addressId = this.id.substring(0, this.id.indexOf("-"));

          navigator.geolocation.getCurrentPosition(function(position) {
            var geocoder = new google.maps.Geocoder();
            geocoder.geocode({
              "location": new google.maps.LatLng(position.coords.latitude, position.coords.longitude)
            },
            function(results, status) {
              if (status == google.maps.GeocoderStatus.OK)
                $("#" + addressId).val(results[0].formatted_address);
              else
                $("#error").append("Unable to retrieve your address<br />");
            });
          },
          function(positionError){
            $("#error").append("Error: " + positionError.message + "<br />");
          },
          {
            enableHighAccuracy: true,
            timeout: 10 * 1000 // 10 seconds
          });
        });

        $("#calculate-route").submit(function(event) {
          event.preventDefault();
          calculateRoute($("#from").val(), $("#to").val());
        });
      });
    </script>
    <style type="text/css">
      #map {
        width: 500px;
        height: 400px;
        margin-top: 10px;
      }
    </style>
    
    
    
    
    
    
           <title>Greater Noida Yellow pages</title>
           <link rel="stylesheet" href="css/main-style.css" type="text/css"/>
           <link rel="stylesheet" href="css/nivo-slider.css" type="text/css" media="screen" />
    
         <script type="text/javascript" src="js/jquery.js"></script>
    
          <script type="text/javascript" src="js/jquery.nivo.slider.pack.js"></script>
          <script type="text/javascript" src="js/jquery.cycle.all.2.74.js"></script>
		  <title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Image Slider Tutorial, Image Slider Download" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<style type="text/css">a#vlb{display:none}</style>
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

          



    <script src="js/jquery.scrollbox.js"></script>
   </head>

  <body>
     <div id="container">

           <div id="header">

                 <div id="header-logo" bgcolor="yellow">
				 <img src="images/logo.png" width="170px;"/>
           </div>

                 <div id="header-banner">
				        <!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="data1/images/g4.jpg" alt="g4" title="g4" id="wows0"/></a>
<a href="#"><img src="data1/images/g5.jpg" alt="g5" title="g5" id="wows1"/></a>
<a href="#"><img src="data1/images/g6.jpg" alt="g6" title="g6" id="wows2"/></a>
<a href="#"><img src="data1/images/g7.jpg" alt="g7" title="g7" id="wows3"/></a>
<a href="#"><img src="data1/images/g8.jpg" alt="g8" title="g8" id="wows4"/></a>
<a href="#"><img src="data1/images/g9.jpg" alt="g9" title="g9" id="wows5"/></a>
<a href="#"><img src="data1/images/g10.jpg" alt="g10" title="g10" id="wows6"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="g4"><img src="data1/tooltips/g4.jpg" alt="g4"/>1</a>
<a href="#wows1" title="g5"><img src="data1/tooltips/g5.jpg" alt="g5"/>2</a>
<a href="#wows2" title="g6"><img src="data1/tooltips/g6.jpg" alt="g6"/>3</a>
<a href="#wows3" title="g7"><img src="data1/tooltips/g7.jpg" alt="g7"/>4</a>
<a href="#wows4" title="g8"><img src="data1/tooltips/g8.jpg" alt="g8"/>5</a>
<a href="#wows5" title="g9"><img src="data1/tooltips/g9.jpg" alt="g9"/>6</a>
<a href="#wows6" title="g10"><img src="data1/tooltips/g10.jpg" alt="g10"/>7</a>
</div></div>
<a style="display:none" href="http://wowslider.com">Image Slider Plugin by WOWSlider.com v1.7</a>
	<a href="#" class="ws_frame"></a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
                                 
								   
                 </div>

                <div id="header-plugin">
                      <div class="box"><img src="images/logo1.png" width="240px" height="130px;"/></div>
                      <div class="box">
                           
                      </div>
                      
                 </div>

           </div>

          <div id="menu">
		                  <ul>
						         <li><a href="index.jsp">Home</a></li>
								 <li><a href="about_us.jsp">About Us</a></li>
								 <li><a href="contact_us.jsp">Contact Us</a></li>
								 <li><a href="category.jsp">Category</a></li>
								 <li><a href="login.jsp">Login</a></li>
								 <li><a href="loc.jsp">Location Tracker</a></li>
								 
						  </ul>
                
         
         </div>
         
         </body>
         </html>